### ISSUE TITLE
Update documentation - datree centralized policy

### ISSUE THREAD

**Issue by Shivam-Katare** [datreeio/docs#63]
We should add more clarity to this [page.](https://hub.datree.io/setup/centralized-policy#running-checks-against-the-new-policy) I improved the documentation's clarity and removed all grammar and punctuation errors. And also made the document easier to understand. 

### For Example👇
# Previously
![23 07 2022_12 29 11_REC](https://user-images.githubusercontent.com/91705825/180594360-1721cf53-2c2f-4768-af01-255b96ec37e0.png)

# After Updating

![23 07 2022_12 30 27_REC](https://user-images.githubusercontent.com/91705825/180594379-5ccdd922-4c82-42a3-b6c9-aa730e63cf1e.png)

**Comment by eyarz** [comment]
@Shivam-Katare thank you for your work, but if you will open a PR it will be easier to review and accept your suggestion :)
https://github.com/datreeio/docs/blob/main/docs/setup/centralized-policy/index.mdx

**Comment by Shivam-Katare** [comment]
Okay, @eyarz, I will open a PR.

**Comment by Shivam-Katare** [comment]
> @Shivam-Katare thank you for your work, but if you will open a PR it will be easier to review and accept your suggestion :) https://github.com/datreeio/docs/blob/main/docs/setup/centralized-policy/index.mdx

@eyarz  I raised the PR. You can check it now.

**Comment by eyarz** [comment]
Awesome :) 
someone from our maintainers' team will review it soon.

**Comment by hadar-co** [comment]
PR was merged:)

Thanks @Shivam-Katare

**Comment by Shivam-Katare** [comment]
> PR was merged:)
> 
> Thanks @Shivam-Katare

I am glad to contribute to it.
